### ISSUE TITLE
如何才能生成pdf

### ISSUE THREAD

**Issue by 19950520** [gwuhaolin/resume#2]
npm run dev 可以运行
npm run pub 这步就不行了 
网上搜索没有搜到
![image](https://user-images.githubusercontent.com/13502844/42358133-ad127bce-810d-11e8-93de-79f609d08188.png)

**Comment by gwuhaolin** [comment]
这是window系统导致的，`NODE_ENV=production`是Linux系统上注册环境变量的语法，Windows系统的语法不是这样的。

**Comment by xypecho** [comment]
@19950520  windows下设置成 `"pub": "set NODE_ENV=dev && webpack --config webpack-dist.config.js && rm -rf .public"`  即可

**Comment by 19950520** [comment]
@xypecho 谢谢 如果没错的话 是在package.json 这个文件里进行修改  不过我改完执行是这样的
![image](https://user-images.githubusercontent.com/13502844/42417437-ecc757e8-82bc-11e8-97d6-4c7888b5107f.png)
我对git 命令并不太熟
在webpack-dist.config.js 这个文件里的105行可以改gitPage的地址
我现在是用浏览器打开 并打印成pdf的

**Comment by qdchenyixuan** [comment]
我这里只生成了打包后的html和css没有PDF文件（环境为mac），请问如何解决呢？谢谢！

**Comment by gwuhaolin** [comment]
> 我这里只生成了打包后的html和css没有PDF文件（环境为mac），请问如何解决呢？谢谢！

确保安装了chrome
