### ISSUE TITLE
github pages已经用来搭博客了，再执行npm run pub会把博客内容覆盖么

### ISSUE THREAD

**Issue by xypecho** [gwuhaolin/resume#3]
update,执行了npm run pub之后，并没有覆盖github pages上面的博客，当然简历也没能成功在github pages上展示

**Comment by haojianxun** [comment]
@pointline  我是最后一步不成功 报错如下:
cnpm run pub

> @ pub E:\resume
> NODE_ENV=production webpack --config webpack-dist.config.js && rm -rf .public

'NODE_ENV' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ pub: `NODE_ENV=production webpack --config webpack-dist.config.js && rm -rf .public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ pub script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-05T06_31_46_512Z-debug.log

**Comment by pointline** [comment]
@haojianxun 那个乱码是什么，你可以看debug.log日志，查询具体情况

**Comment by haojianxun** [comment]
@pointline  看 错误的话是因为 pub脚本导致 NODE_ENV=production webpack --config webpack-dist.config.js && rm -rf .public
dev倒是可以运行 其他的就看不出什么了
我的环境是nodejs已经安装 npm用的淘宝的镜像 用cnpm代替npm
之后git clone foke过来的仓库
进入仓库  执行 
cnpm i  完成
cnpm run dev 完成 (浏览器跳出一个预览页面)
cnpm run pub  报pub脚本error 就是上面的错误  debug.log日志也一样

**Comment by haojianxun** [comment]
@pointline 已经解决了 删除了package.json中` "pub": "NODE_ENV=production webpack --config webpack-dist.config.js && rm -rf .public"` 里的`NODE_ENV=production `  之后运行完成  感谢!!!
