### ISSUE TITLE
生成的PDF丢失了一部分样式

### ISSUE THREAD

**Issue by Messiahhh** [gwuhaolin/resume#6]
content-hd 里面的样式，例如背景，图标都丢失了.不知道原因

**Comment by NBSeven** [comment]
在样式文件里有个媒体查询的属性@media print ，把对应的样式设置注释掉就好了。我觉着是留着好看些，不知道作者为啥要区分开。

**Comment by NBSeven** [comment]
> content-hd 里面的样式，例如背景，图标都丢失了.不知道原因

在样式文件里有个媒体查询的属性@media print ，把对应的样式设置注释掉就好了。我觉着是留着好看些，不知道作者为啥要区分开。

**Comment by gwuhaolin** [comment]
去掉是方便打印纸张阅读
